# Generated by Django 4.1 on 2025-04-11 13:29

from django.db import migrations, models

import cinema.models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_movie_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviesession",
            name="movie_image",
            field=models.ImageField(
                null=True, upload_to=cinema.models.movie_session_image_path
            ),
        ),
    ]
